/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * dog
 * OpenAPI spec version: 1.0.0
 */

/**
 * A charity object
 */
export interface Charity {
  codes?: string[];
  id: number;
  name: string;
}
