/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * dog
 * OpenAPI spec version: 1.0.0
 */

/**
 * A dog object
 */
export interface Dog {
  age: number;
  breed: string;
  charityId: number;
  id: number;
  name: string;
}
