/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * dog
 * OpenAPI spec version: 1.0.0
 */

export type GetDogsParams = {
/**
 * Breed
 */
breed?: string;
/**
 * Name
 */
name?: string;
/**
 * Name
 */
ageFrom?: number;
/**
 * Name
 */
ageTo?: number;
};
