/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * dog
 * OpenAPI spec version: 1.0.0
 */

export * from './charity';
export * from './createDogBody';
export * from './dog';
export * from './postAuthLogin200';
export * from './postAuthLoginBody';
export * from './postAuthRegister201';
export * from './postAuthRegisterBody';
export * from './postCharitiesBody';
export * from './putCharitiesBody';
export * from './updateDogBody';
export * from './user';