/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * dog
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateDogBody {
  age: number;
  breed: string;
  image: number;
  name: string;
}
