/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * dog
 * OpenAPI spec version: 1.0.0
 */

/**
 * A user object
 */
export interface User {
  charityId?: number;
  id: number;
  role: string;
  username: string;
}
